List<String> allPengeluaran = [
  "Kontribusi Yayasan",
  "Honor Guru MI",
  "Honor Keamanan",
  "Honor Kebersihan",
  "Honor Pendamping",
  "Komputer",
  "Pramuka",
  "Paskibra",
  "Kaligrafi",
  "Pencak Silat",
  "Futsal & Sewa Lapangan",
  "Qiro'at",
  "Listrik / Telepon",
  "Internet",
  "Administrasi / ATK",
  "Sarana dan Prasarana",
  "PKG / PKM",
  "Transport Dinas",
  "Biaya Rapat",
  "Konsumsi Guru",
  "Langganan Sampah",
  "Perbankan",
  "Bos Buku",
  "Operasional Bos + LPJ",
  "BTT",
];
