List<String> allPengeluaran = [
  "Administrasi atau ATK",
  "Biaya Rapat",
  "Bos Buku",
  "BTT",
  "Futsal dan Sewa Lapangan",
  "Honor Guru MI",
  "Honor Keamanan",
  "Honor Kebersihan",
  "Honor Pendamping",
  "Internet",
  "Kaligrafi",
  "Komputer",
  "Konsumsi Guru",
  "Kontribusi Yayasan",
  "Langganan Sampah",
  "Listrik atau Telepon",
  "Operasional Bos + LPJ",
  "Paskibra",
  "Pencak Silat",
  "Perbankan",
  "PKG atau PKM",
  "Pramuka",
  "Qiro'at",
  "Sarana dan Prasarana",
  "Transport Dinas",
];
